/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasYenConverter() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.yenConverter(), "app should have a yen converter");
    }
    @Test void appHasEuroConverter() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.euroConverter(), "app should have a euro converter");
    }
}
